name: Lean Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      uses: leanprover/lean-action@v1
      with:
        use-mathlib-cache: true
